In [1]:
print("Horizon1 is ready!")

Horizon1 is ready!

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
print("Environment is ready")

Environment is ready

In [6]:
import wbdata

print("World Bank connection ready!")

ModuleNotFoundError: No module named 'wbdata'

In [7]:
import sys

print(sys.executable)

C:\Users\Couli\anaconda3\python.exe

In [1]:
import wbdata

print("World Bank connection ready!")

World Bank connection ready!

In [2]:
import wbdata

indicators = wbdata.get_indicator()

print(indicators.head())

AttributeError: module 'wbdata' has no attribute 'get_indicator'

In [3]:
import wbdata

print(wbdata.__version__)
print(dir(wbdata))

1.1.0
['Client', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'cache', 'client', 'dates', 'fetcher', 'get_countries', 'get_data', 'get_dataframe', 'get_default_client', 'get_incomelevels', 'get_indicators', 'get_lendingtypes', 'get_series', 'get_sources', 'get_topics', 'lru_cache', 'version']

In [4]:
indicators = wbdata.get_indicators()

print(indicators.head())

AttributeError: 'SearchResult' object has no attribute 'head'

In [5]:
indicators = wbdata.get_indicators()

print(type(indicators))
print(indicators)

<class 'wbdata.client.SearchResult'>

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

In [6]:
indicators = wbdata.get_indicators()

print(indicators[:10])

[{'id': '1.0.HCount.1.90usd', 'name': 'Poverty Headcount ($1.90 a day)', 'unit': '', 'source': {'id': '37', 'value': 'LAC Equity Lab'}, 'sourceNote': 'The poverty headcount index measures the proportion of the population with daily per capita income (in 2011 PPP) below the poverty line.', 'sourceOrganization': 'LAC Equity Lab tabulations of SEDLAC (CEDLAS and the World Bank).', 'topics': [{'id': '11', 'value': 'Poverty '}]}, {'id': '1.0.HCount.2.5usd', 'name': 'Poverty Headcount ($2.50 a day)', 'unit': '', 'source': {'id': '37', 'value': 'LAC Equity Lab'}, 'sourceNote': 'The poverty headcount index measures the proportion of the population with daily per capita income (in 2005 PPP) below the poverty line.', 'sourceOrganization': 'LAC Equity Lab tabulations of SEDLAC (CEDLAS and the World Bank).', 'topics': [{'id': '11', 'value': 'Poverty '}]}, {'id': '1.0.HCount.Mid10to50', 'name': 'Middle Class ($10-50 a day) Headcount', 'unit': '', 'source': {'id': '37', 'value': 'LAC Equity Lab'}, 'sourceNote': 'The poverty headcount index measures the proportion of the population with daily per capita income (in 2005 PPP) below the poverty line.', 'sourceOrganization': 'LAC Equity Lab tabulations of SEDLAC (CEDLAS and the World Bank).', 'topics': [{'id': '11', 'value': 'Poverty '}]}, {'id': '1.0.HCount.Ofcl', 'name': 'Official Moderate Poverty Rate-National', 'unit': '', 'source': {'id': '37', 'value': 'LAC Equity Lab'}, 'sourceNote': 'The poverty headcount index measures the proportion of the population with daily per capita income below the official poverty line developed by each country.', 'sourceOrganization': 'LAC Equity Lab tabulations of data from National Statistical Offices.', 'topics': [{'id': '11', 'value': 'Poverty '}]}, {'id': '1.0.HCount.Poor4uds', 'name': 'Poverty Headcount ($4 a day)', 'unit': '', 'source': {'id': '37', 'value': 'LAC Equity Lab'}, 'sourceNote': 'The poverty headcount index measures the proportion of the population with daily per capita income (in 2005 PPP) below the poverty line.', 'sourceOrganization': 'LAC Equity Lab tabulations of SEDLAC (CEDLAS and the World Bank).', 'topics': [{'id': '11', 'value': 'Poverty '}]}, {'id': '1.0.HCount.Vul4to10', 'name': 'Vulnerable ($4-10 a day) Headcount', 'unit': '', 'source': {'id': '37', 'value': 'LAC Equity Lab'}, 'sourceNote': 'The poverty headcount index measures the proportion of the population with daily per capita income (in 2005 PPP) below the poverty line.', 'sourceOrganization': 'LAC Equity Lab tabulations of SEDLAC (CEDLAS and the World Bank).', 'topics': [{'id': '11', 'value': 'Poverty '}]}, {'id': '1.0.PGap.1.90usd', 'name': 'Poverty Gap ($1.90 a day)', 'unit': '', 'source': {'id': '37', 'value': 'LAC Equity Lab'}, 'sourceNote': 'The poverty gap captures the mean aggregate income or consumption shortfall relative to the poverty line across the entire population. It measures the total resources needed to bring all the poor to the level of the poverty line (averaged over the total population). ', 'sourceOrganization': 'LAC Equity Lab tabulations of SEDLAC (CEDLAS and the World Bank).', 'topics': [{'id': '11', 'value': 'Poverty '}]}, {'id': '1.0.PGap.2.5usd', 'name': 'Poverty Gap ($2.50 a day)', 'unit': '', 'source': {'id': '37', 'value': 'LAC Equity Lab'}, 'sourceNote': 'The poverty gap captures the mean aggregate income or consumption shortfall relative to the poverty line across the entire population. It measures the total resources needed to bring all the poor to the level of the poverty line (averaged over the total population). ', 'sourceOrganization': 'LAC Equity Lab tabulations of SEDLAC (CEDLAS and the World Bank).', 'topics': [{'id': '11', 'value': 'Poverty '}]}, {'id': '1.0.PGap.Poor4uds', 'name': 'Poverty Gap ($4 a day)', 'unit': '', 'source': {'id': '37', 'value': 'LAC Equity Lab'}, 'sourceNote': 'The poverty gap captures the mean aggregate income or consumption shortfall relative to the poverty line across the entire population. It measures the total resources needed to bring all the poor to the level of the poverty line (averaged over the total population). ', 'sourceOrganization': 'LAC Equity Lab tabulations of SEDLAC (CEDLAS and the World Bank).', 'topics': [{'id': '11', 'value': 'Poverty '}]}, {'id': '1.0.PSev.1.90usd', 'name': 'Poverty Severity ($1.90 a day)', 'unit': '', 'source': {'id': '37', 'value': 'LAC Equity Lab'}, 'sourceNote': 'The poverty severity index combines information on both poverty and inequality among the poor by averaging the squares of the poverty gaps relative the poverty line', 'sourceOrganization': 'LAC Equity Lab tabulations of SEDLAC (CEDLAS and the World Bank).', 'topics': [{'id': '11', 'value': 'Poverty '}]}]

In [7]:
countries = wbdata.get_countries()

print(countries[:5])

[{'id': 'ABW', 'iso2Code': 'AW', 'name': 'Aruba', 'region': {'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Latin America & Caribbean '}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'HIC', 'iso2code': 'XD', 'value': 'High income'}, 'lendingType': {'id': 'LNX', 'iso2code': 'XX', 'value': 'Not classified'}, 'capitalCity': 'Oranjestad', 'longitude': '-70.0167', 'latitude': '12.5167'}, {'id': 'AFE', 'iso2Code': 'ZH', 'name': 'Africa Eastern and Southern', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'AFG', 'iso2Code': 'AF', 'name': 'Afghanistan', 'region': {'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Middle East, North Africa, Afghanistan & Pakistan'}, 'adminregion': {'id': 'MNA', 'iso2code': 'XQ', 'value': 'Middle East, North Africa, Afghanistan & Pakistan (excluding high income)'}, 'incomeLevel': {'id': 'LIC', 'iso2code': 'XM', 'value': 'Low income'}, 'lendingType': {'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}, 'capitalCity': 'Kabul', 'longitude': '69.1761', 'latitude': '34.5228'}, {'id': 'AFR', 'iso2Code': 'A9', 'name': 'Africa', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}, {'id': 'AFW', 'iso2Code': 'ZI', 'name': 'Africa Western and Central', 'region': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'adminregion': {'id': '', 'iso2code': '', 'value': ''}, 'incomeLevel': {'id': 'NA', 'iso2code': 'NA', 'value': 'Aggregates'}, 'lendingType': {'id': '', 'iso2code': '', 'value': 'Aggregates'}, 'capitalCity': '', 'longitude': '', 'latitude': ''}]

In [8]:
import wbdata

gdp = wbdata.get_data(
    "NY.GDP.MKTP.CD",
    country="CIV"
)

print(gdp[:5])

[{'indicator': {'id': 'NY.GDP.MKTP.CD', 'value': 'GDP (current US$)'}, 'country': {'id': 'CI', 'value': "Cote d'Ivoire"}, 'countryiso3code': 'CIV', 'date': '2025', 'value': 99773555666.1988, 'unit': '', 'obs_status': '', 'decimal': 0}, {'indicator': {'id': 'NY.GDP.MKTP.CD', 'value': 'GDP (current US$)'}, 'country': {'id': 'CI', 'value': "Cote d'Ivoire"}, 'countryiso3code': 'CIV', 'date': '2024', 'value': 87113179149.284, 'unit': '', 'obs_status': '', 'decimal': 0}, {'indicator': {'id': 'NY.GDP.MKTP.CD', 'value': 'GDP (current US$)'}, 'country': {'id': 'CI', 'value': "Cote d'Ivoire"}, 'countryiso3code': 'CIV', 'date': '2023', 'value': 80780312569.1646, 'unit': '', 'obs_status': '', 'decimal': 0}, {'indicator': {'id': 'NY.GDP.MKTP.CD', 'value': 'GDP (current US$)'}, 'country': {'id': 'CI', 'value': "Cote d'Ivoire"}, 'countryiso3code': 'CIV', 'date': '2022', 'value': 70922824813.9102, 'unit': '', 'obs_status': '', 'decimal': 0}, {'indicator': {'id': 'NY.GDP.MKTP.CD', 'value': 'GDP (current US$)'}, 'country': {'id': 'CI', 'value': "Cote d'Ivoire"}, 'countryiso3code': 'CIV', 'date': '2021', 'value': 72794636653.7793, 'unit': '', 'obs_status': '', 'decimal': 0}]

In [9]:
indicators = {
    "GDP": "NY.GDP.MKTP.CD",
    "GDP_growth": "NY.GDP.MKTP.KD.ZG",
    "GDP_per_capita": "NY.GDP.PCAP.CD",
    "Inflation": "FP.CPI.TOTL.ZG",
    "Unemployment": "SL.UEM.TOTL.ZS",
    "Exports": "NE.EXP.GNFS.CD",
    "Imports": "NE.IMP.GNFS.CD",
    "Investment": "NE.GDI.TOTL.ZS"
}

print(indicators)

{'GDP': 'NY.GDP.MKTP.CD', 'GDP_growth': 'NY.GDP.MKTP.KD.ZG', 'GDP_per_capita': 'NY.GDP.PCAP.CD', 'Inflation': 'FP.CPI.TOTL.ZG', 'Unemployment': 'SL.UEM.TOTL.ZS', 'Exports': 'NE.EXP.GNFS.CD', 'Imports': 'NE.IMP.GNFS.CD', 'Investment': 'NE.GDI.TOTL.ZS'}

In [ ]:
data = {}

for name, indicator in indicators.items():
    result = wbdata.get_data(
        indicator,
        country="CIV"
    )
    data[name] = result

print(data.keys())

In [11]:
print("Kernel is working")

Kernel is working

In [12]:
data = wbdata.get_dataframe(
    indicators,
    country="CIV"
)

print(data.head())

RuntimeError: Got error 120 (Invalid value): The provided parameter value is not valid

In [13]:
indicator_codes = {
    code: name
    for name, code in indicators.items()
}

print(indicator_codes)

{'NY.GDP.MKTP.CD': 'GDP', 'NY.GDP.MKTP.KD.ZG': 'GDP_growth', 'NY.GDP.PCAP.CD': 'GDP_per_capita', 'FP.CPI.TOTL.ZG': 'Inflation', 'SL.UEM.TOTL.ZS': 'Unemployment', 'NE.EXP.GNFS.CD': 'Exports', 'NE.IMP.GNFS.CD': 'Imports', 'NE.GDI.TOTL.ZS': 'Investment'}

In [14]:
data = wbdata.get_dataframe(
    indicator_codes,
    country="CIV",
    date=("2010", "2025")
)

print(data.head())

               GDP  GDP_growth  GDP_per_capita  Inflation  Unemployment  \
date
2025  9.977356e+10    6.500000     3050.102023   0.125039         2.323
2024  8.711318e+10    6.019535     2727.893522   3.450530         2.273
2023  8.078031e+10    6.600000     2591.965905   4.369723         2.263
2022  7.092282e+10    6.399884     2333.371283   5.233529         2.310
2021  7.279464e+10    7.062537     2455.981276   4.159197         2.623

           Exports       Imports  Investment
date
2025  2.971795e+10  2.471642e+10   19.301914
2024  2.267383e+10  2.198473e+10   20.869851
2023  1.812334e+10  2.131119e+10   24.544448
2022  1.721110e+10  2.028324e+10   27.485312
2021  1.623049e+10  1.661011e+10   23.575317

In [15]:
print("Dataset shape:")
print(data.shape)

print("\nMissing values:")
print(data.isna().sum())

print("\nData types:")
print(data.dtypes)

Dataset shape:
(16, 8)

Missing values:
GDP               0
GDP_growth        0
GDP_per_capita    0
Inflation         0
Unemployment      0
Exports           0
Imports           0
Investment        0
dtype: int64

Data types:
GDP               float64
GDP_growth        float64
GDP_per_capita    float64
Inflation         float64
Unemployment      float64
Exports           float64
Imports           float64
Investment        float64
dtype: object

In [16]:
data.describe()

,GDP,GDP_growth,GDP_per_capita,Inflation,Unemployment,Exports,Imports,Investment
count,1.600000e+01,16.000000,16.000000,16.000000,16.000000,1.600000e+01,1.600000e+01,16.000000
mean,5.872428e+10,5.990931,2107.996182,2.129782,3.492312,1.535751e+10,1.501432e+10,22.088658
std,1.925902e+10,3.681531,436.081786,1.760637,1.825064,4.782016e+09,4.489226e+09,2.384666
min,3.493631e+10,-5.370447,1546.946018,0.125039,1.896000,1.170351e+10,1.080062e+10,16.593719
25%,4.505131e+10,6.304796,1807.578568,0.713854,2.319750,1.265781e+10,1.209012e+10,20.856803
50%,5.551741e+10,6.784711,2061.115794,1.278005,2.605500,1.333561e+10,1.301264e+10,22.121364
75%,7.139078e+10,7.248903,2364.023781,3.627697,3.519250,1.647564e+10,1.752839e+10,23.242839
max,9.977356e+10,10.760213,3050.102023,5.233529,7.223000,2.971795e+10,2.471642e+10,27.485312

In [17]:
print("Duplicate rows:", data.duplicated().sum())

print("\nIndex name:")
print(data.index.name)

print("\nIndex type:")
print(data.index.dtype)

print("\nYears:")
print(data.index.tolist())

Duplicate rows: 0

Index name:
date

Index type:
object

Years:
['2025', '2024', '2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016', '2015', '2014', '2013', '2012', '2011', '2010']

In [18]:
data.index = data.index.astype(int)
data = data.sort_index()

print(data.head())

               GDP  GDP_growth  GDP_per_capita  Inflation  Unemployment  \
date
2010  3.493631e+10    6.848049     1553.548870   1.226456         6.607
2011  3.669371e+10   -5.370447     1596.628266   4.912434         7.144
2012  3.630230e+10    7.620412     1546.946018   1.304511         7.223
2013  4.276024e+10   10.760213     1786.158620   2.581170         4.255
2014  4.884301e+10    9.372000     1991.365394   0.448682         3.274

           Exports       Imports  Investment
date
2010  1.170351e+10  1.186904e+10   21.681055
2011  1.294605e+10  1.080062e+10   16.593719
2012  1.269945e+10  1.282146e+10   20.450817
2013  1.246906e+10  1.248269e+10   22.909801
2014  1.375270e+10  1.246642e+10   22.620456

In [19]:
data

,GDP,GDP_growth,GDP_per_capita,Inflation,Unemployment,Exports,Imports,Investment
date,,,,,,,,
2010,3.493631e+10,6.848049,1553.548870,1.226456,6.607,1.170351e+10,1.186904e+10,21.681055
2011,3.669371e+10,-5.370447,1596.628266,4.912434,7.144,1.294605e+10,1.080062e+10,16.593719
2012,3.630230e+10,7.620412,1546.946018,1.304511,7.223,1.269945e+10,1.282146e+10,20.450817
2013,4.276024e+10,10.760213,1786.158620,2.581170,4.255,1.246906e+10,1.248269e+10,22.909801
2014,4.884301e+10,9.372000,1991.365394,0.448682,3.274,1.375270e+10,1.246642e+10,22.620456
2015,4.581501e+10,7.194949,1814.718551,1.251500,2.573,1.253287e+10,1.161867e+10,23.388149
2016,4.840776e+10,7.172760,1862.595971,0.723178,1.896,1.207380e+10,1.095163e+10,23.194402
2017,5.251234e+10,7.410762,1964.299303,0.685881,3.272,1.339001e+10,1.216381e+10,20.817659
2018,5.852248e+10,4.843146,2130.866194,0.401298,2.852,1.328121e+10,1.366108e+10,22.252790
2019,6.038289e+10,6.721372,2141.768362,0.790856,2.401,1.368306e+10,1.328419e+10,21.989938
2020,6.302785e+10,0.699729,2179.729348,2.412526,2.588,1.323173e+10,1.320381e+10,21.742893
2021,7.279464e+10,7.062537,2455.981276,4.159197,2.623,1.623049e+10,1.661011e+10,23.575317
2022,7.092282e+10,6.399884,2333.371283,5.233529,2.310,1.721110e+10,2.028324e+10,27.485312
2023,8.078031e+10,6.600000,2591.965905,4.369723,2.263,1.812334e+10,2.131119e+10,24.544448
2024,8.711318e+10,6.019535,2727.893522,3.450530,2.273,2.267383e+10,2.198473e+10,20.869851
2025,9.977356e+10,6.500000,3050.102023,0.125039,2.323,2.971795e+10,2.471642e+10,19.301914

In [20]:
data.to_csv(
    "../data/raw/cote_divoire_economic_indicators_2010_2025.csv"
)

print("Raw economic data saved successfully.")

Raw economic data saved successfully.

In [21]:
import pandas as pd

raw_data = pd.read_csv(
    "../data/raw/cote_divoire_economic_indicators_2010_2025.csv",
    index_col="date"
)

print(raw_data.shape)
print(raw_data.head())
print(raw_data.tail())

(16, 8)
               GDP  GDP_growth  GDP_per_capita  Inflation  Unemployment  \
date
2010  3.493631e+10    6.848049     1553.548870   1.226456         6.607
2011  3.669371e+10   -5.370447     1596.628266   4.912434         7.144
2012  3.630230e+10    7.620412     1546.946018   1.304511         7.223
2013  4.276024e+10   10.760213     1786.158620   2.581170         4.255
2014  4.884301e+10    9.372000     1991.365394   0.448682         3.274

           Exports       Imports  Investment
date
2010  1.170351e+10  1.186904e+10   21.681055
2011  1.294605e+10  1.080062e+10   16.593719
2012  1.269945e+10  1.282146e+10   20.450817
2013  1.246906e+10  1.248269e+10   22.909801
2014  1.375270e+10  1.246642e+10   22.620456
               GDP  GDP_growth  GDP_per_capita  Inflation  Unemployment  \
date
2021  7.279464e+10    7.062537     2455.981276   4.159197         2.623
2022  7.092282e+10    6.399884     2333.371283   5.233529         2.310
2023  8.078031e+10    6.600000     2591.965905   4.369723         2.263
2024  8.711318e+10    6.019535     2727.893522   3.450530         2.273
2025  9.977356e+10    6.500000     3050.102023   0.125039         2.323

           Exports       Imports  Investment
date
2021  1.623049e+10  1.661011e+10   23.575317
2022  1.721110e+10  2.028324e+10   27.485312
2023  1.812334e+10  2.131119e+10   24.544448
2024  2.267383e+10  2.198473e+10   20.869851
2025  2.971795e+10  2.471642e+10   19.301914